### ISSUE TITLE
Incompatibility with Quilt Standard Libraries

### ISSUE THREAD

**Issue by magneticflux-** [TropheusJ/stonecutter-recipe-tags#5]
QSL expects `getAvailableRecipes()` to return a correctly sized list here: https://github.com/QuiltMC/quilt-standard-libraries/blob/ef7cb80265918477a69990563b3251acf697bdf0/library/item/item_setting/src/main/java/org/quiltmc/qsl/item/setting/mixin/recipe_remainder/StonecutterOutputSlotMixin.java#L44-L45

The stacktrace:
```
java.lang.IndexOutOfBoundsException: Index 19 out of bounds for length 10
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.2)
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.util.Objects.checkIndex(Objects.java:385)
	at java.util.ArrayList.get(ArrayList.java:427)
	at net.minecraft.screen.StonecutterScreenHandler$2.redirect$ceh001$getRecipeRemainder(StonecutterScreenHandler:1047)
	at net.minecraft.screen.StonecutterScreenHandler$2.onTakeItem(StonecutterScreenHandler:74)
	at net.minecraft.screen.ScreenHandler.method_34249(ScreenHandler:423)
	at java.util.Optional.ifPresent(Optional.java:178)
	at net.minecraft.screen.ScreenHandler.internalOnSlotClick(ScreenHandler:421)
	at net.minecraft.screen.ScreenHandler.onSlotClick(ScreenHandler:293)
	at net.minecraft.client.network.ClientPlayerInteractionManager.clickSlot(ClientPlayerInteractionManager:450)
	at net.minecraft.client.gui.screen.ingame.HandledScreen.onMouseClick(HandledScreen:569)
	at net.minecraft.client.gui.screen.ingame.HandledScreen.mouseClicked(HandledScreen:361)
	at net.minecraft.client.gui.screen.ingame.StonecutterScreen.mouseClicked(StonecutterScreen:150)
	at net.minecraft.client.Mouse.method_1611(Mouse:94)
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:489)
	at net.minecraft.client.Mouse.onMouseButton(Mouse:94)
	at net.minecraft.client.Mouse.method_22686(Mouse:165)
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:103)
	at net.minecraft.client.Mouse.method_22684(Mouse:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem:197)
	at net.minecraft.client.util.Window.swapBuffers(Window:315)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1205)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:768)
	at net.minecraft.client.main.Main.method_44604(Main:244)
	at net.minecraft.client.main.Main.main(Main:51)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.lang.reflect.Method.invoke(Method.java:578)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.lang.reflect.Method.invoke(Method.java:578)
	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74)
```

The full crash report: https://mclo.gs/pYUd7so

**Comment by magneticflux-** [comment]
The actual crash happens here: https://github.com/QuiltMC/quilt-standard-libraries/blob/ef7cb80265918477a69990563b3251acf697bdf0/library/item/item_setting/src/main/java/org/quiltmc/qsl/item/setting/mixin/recipe_remainder/StonecutterOutputSlotMixin.java#L47

Maybe `getAvailableRecipes()` isn't taking into account recipes added like `getStacksToDisplay()` does?

**Comment by magneticflux-** [comment]
@TropheusJ @IMS212 Do you think we could create additional `StonecuttingRecipe`s on-the-fly so mods expecting visible recipes to exist would work? Just hook into `updateInput` and add them?

**Comment by magneticflux-** [comment]
I have a sort-of-working version that removes most of the `Screen` mixins by making a new class extending from `StonecuttingRecipe`:
```java
availableRecipes = new ArrayList<>(world.getRecipeManager().getAllMatches(RecipeType.STONECUTTING, input, world));
for (Item resultItem : items) {
	availableRecipes.add(new StonecuttingRecipe(
			null,
			null,
			null,
			new ItemStack(resultItem, StonecutterRecipeTagManager.getItemCraftCount(resultItem))
	) {
		@Override
		public boolean matches(Inventory inventory, World world) {
			var inputStack = inventory.getStack(0);
			return inputStack.isItemEqual(inputItemStack) && inputStack.getCount() >= StonecutterRecipeTagManager.getItemCraftCount(inputItemStack);
		}
		@Override
		public ItemStack craft(Inventory inventory) {
			if (this.matches(inventory, null))
				return new ItemStack(resultItem, StonecutterRecipeTagManager.getItemCraftCount(resultItem));
			else
				return ItemStack.EMPTY;
		}
	});
	ItemStack stackedItem = new ItemStack(resultItem);
	stacksToDisplay.add(stackedItem);
}
```
![2022-11-19_02 21 16](https://user-images.githubusercontent.com/9124288/202841845-4d7e1459-77c9-42b1-b56f-e5c53f385795.png)

If this is something that would be appreciated, I can clean it up and make a PR.
