### ISSUE TITLE
Incorrectly Packaged Dependencies 1.19.2

### ISSUE THREAD

**Issue by Peach774** [TropheusJ/stonecutter-recipe-tags#7]
I get this error:
Exception in thread "main" java.lang.module.ResolutionException: Modules MixinExtras.rc5 and stonecutter_recipe_tags export package com.llamalad7.mixinextras to module attributefix

I was told this is because a dependency is packaged 'badly'

**Comment by Guinaro** [comment]
Same issue: Can only use stonecutter_recipe_tags-4.0.0+1.19.9b8d04c.forge.jar
Cannot launch with either:
stonecutter_recipe_tags-4.1.1+1.19.012e6ff.forge.jar
or
stonecutter_recipe_tags-4.2.1+1.19.5861878.forge.jar

**Comment by Tschipp** [comment]
Related issue: https://github.com/Tschipp/CarryOn/issues/474

I had made the same issue in my mod here: https://github.com/Tschipp/CarryOn/issues/452
Feel free to copy what I did in my build.gradle: https://github.com/Tschipp/CarryOn/blob/1.19-multiloader/Forge/build.gradle

**Comment by Yourname942** [comment]
I have this issue as well: https://pastebin.com/Nrj5jk8v

`Exception in thread "main" java.lang.module.ResolutionException: Modules MixinExtras.beta._6 and stonecutter_recipe_tags export package com.llamalad7.mixinextras to module pumpkillagersquest

	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)

	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)

	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)

	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)

	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)

	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)

	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)

	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)

	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)

	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)

	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)

	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)

	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)`

**Comment by TropheusJ** [comment]
now using jarjar on forge
